AllCops:
  Exclude:
    - 'test/integration/actual_glib.rb'
    - 'test/integration/actual_gobject.rb'
    - 'test/integration/expected_glib.rb'
    - 'test/integration/expected_gobject.rb'
  TargetRubyVersion: 2.4

# Test describe blocks can be any size
Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

# GirFFI-PrettyPrinter uses a gir_ffi-something naming scheme.
Naming/FileName:
  Enabled: false

# Require at least two dependent lines before suggesting a guard clause
Style/GuardClause:
  MinBodyLength: 2

# Prefer symbols to look like symbols
Style/SymbolArray:
  EnforcedStyle: brackets

inherit_from: .rubocop_todo.yml
