sudo: required
dist: trusty
language: ruby

before_install:
  - sudo apt-get update
  - sudo apt-get install libgirepository1.0-dev gobject-introspection
  - gem update --system

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

script: "bundle exec rake test:unit"

branches:
  only:
    - master
