language: ruby

dist: xenial

before_install:
  - sudo apt-get update
  # Provides libgirepository-1.0.so.1
  - sudo apt-get install libgirepository-1.0-1

cache:
  bundler: true

script: "bundle exec rake test:unit"

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

branches:
  only:
    - master
